config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  devise_for :users, path_names:  { sign_in: "login", sign_out: "logout" },
                     controllers: {
                                    registrations: "user/registrations"
                                  }


  #===============Api Routes================
  require 'api_constraints'

   namespace :api, defaults: { format: :json } do
       # scope per version of api
       scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do

         resources :sessions, :only      => [:create, :destroy]
         match '/login'                  => 'sessions#create', :via => [:options, :post]
         post '/logout/:user_id'         => 'sessions#destroy'

         match '/reset_password'         => 'users#reset_password', :via => [:post]
         match '/users/:id'              => 'users#update', :via => [:options, :put, :post]
        #  get '/matches'                  => 'matches#show'

         resources :users, :only         => [:show, :create, :update]

         resources :dealerships, :only   => [:index, :show] do
           resources :sales_reps, :controller => 'sales_reps', :only => [:index, :show]
           resources :service_reps, :controller => 'service_reps', :only => [:index, :show]
         end

         resources :messages

         resources :conversations do
          resources :messages
         end
     end
   end
   #==========================================

  resources :users, only: [:index, :show, :destroy]
  resources :moderators, :controller => 'moderators'
  resources :sales_reps, :controller => 'sales_reps'
  resources :service_reps, :controller => 'service_reps'
  # devise_for :users
  
  resources :conversations do
   resources :messages
  end

  put 'moderators/:id/edit', to: 'moderators#update'
  put 'sales_reps/:id/edit', to: 'sales_reps#update'
  put 'service_reps/:id/edit', to: 'service_reps#update'

  resources :dealerships
  resources :push_notifications
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/push_notification.rb
require 'open-uri'
require 'net/http'

class PushNotification < ApplicationRecord
  belongs_to :user
  after_create :upload_notification_to_ionic

  validates :message, presence: true
  validates :tokens, presence: true

  # attribute :tokens, :string, array: true
  serialize :tokens, Array
  serialize :sent_to, Array

private
  def upload_notification_to_ionic
    puts self.tokens.to_json

    # user_id = self.sent_to
    # badge_count = Conversation.where('(recipient_id= ? AND recipient_read= ?) OR (sender_id= ? AND sender_read= ?)', user_id, false, user_id, false).count;

    params = {
      "tokens" => self.tokens,
      "profile" => ENV['IONIC_PUSH_ENV'],
      "notification":{
        "payload": {
          "user_message": "0"
        },
        "message": self.message,
        "android":{
          "title": "Crescent Ford",
          "sound": "true"
        },
         "ios": {
              "title": "Crescent Ford",
              "sound": "true"
              # ,
              # "badge": badge_count
            }
      }
    }

    uri = URI.parse('https://api.ionic.io/push/notifications')
    https = Net::HTTP.new(uri.host,uri.port)
    https.use_ssl = true
    req = Net::HTTP::Post.new(uri.path)
    req['Authorization'] = ENV['IONIC_API_TOKEN']
    req['Content-Type'] = 'application/json'
    req.body = params.to_json
    res = https.request(req)
    puts res.body
  end
end

app/controllers/push_notifications_controller.rb
class PushNotificationsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_push_notification, only: [:destroy]

  def index
    # @push_notifications = PushNotification.all
    @push_notifications= PushNotification.all
  end

  def show
  end

  def new
    @push_notification = PushNotification.new
    @customers = User.where.not('device_token' => nil)
  end

  def edit
  end

  def create
    @push_notification = PushNotification.new(push_notification_params)
    @push_notification.user_id = current_user.id

    @push_notification.sent_to = params[:tokens]
    @push_notification.sent_to.each do |t|
      device_token = User.find(t).device_token
      @push_notification.tokens.push(device_token) unless device_token.nil?
    end

    respond_to do |format|
      if @push_notification.save
        format.html { redirect_to push_notifications_path, notice: 'Push Notification was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @push_notification.destroy
    respond_to do |format|
      format.html { redirect_to push_notifications_path, notice: 'Push Notification was successfully destroyed.' }
    end
  end

  private


    # Use callbacks to share common setup or constraints between actions.
    def set_push_notification
      @push_notification = PushNotification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def push_notification_params
      params.fetch(:push_notification, {}).permit(:message, :sent_to, :user_id, tokens:[])
    end
end

app/views/push_notifications/index.html.erb
<div class="col-lg-12">
  <div class="row">
    <h1 class="page-heading">Push Notifications</h1>
  </div>
<div class="row text-right">
    <%= link_to root_path, :class => "btn btn-info" do %>
      <i class="fa fa-chevron-circle-left fa-fw" aria-hidden="true"></i>  Dashboard
    <% end %>
    <%= link_to "Send Push Notification", new_push_notification_path, :class=>"btn btn-warning" if current_user.has_role? :admin%>
</div>

<div class="row" style="padding: 2rem 0">
  <div class="col-sm-12" style="padding:0">
    <!-- BEGIN BORDERED TABLE PORTLET-->
    <div class="portlet light portlet-fit ">
        <div class="portlet-body" style="padding-top: 15px;">
            <div class="table-scrollable table-scrollable-borderless" style="overflow: visible !imporant;">
                <table class="table table-striped table-bordered table-hover table-checkable order-column" id="push_notifications_index_table" style="width:100% important!">
                    <thead>
                        <tr class="uppercase" >
                            <th style=" color: #455A64"> Message </th>
                            <th style=" color: #455A6A"> Date Sent </th>
                            <th style=" color: #455A64"> Actions </th>
                        </tr>
                    </thead>
                    <tbody>
                      <% @push_notifications.each  do | notification| %>
                        <tr>
                          <td style="text-align:left; padding-left:10px"><%= notification.message %></td>
                          <td>
                            <%= notification.created_at.strftime("%m/%d/%Y at %I:%M%p") %>
                          </td>
                          <td>
                            <%= link_to 'Remove', notification, :class=>"btn red btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- END BORDERED TABLE PORTLET-->
  </div>
  </div>
</div>

app/views/push_notifications/new.html.erb
<div class="col-xs-12 col-lg-8 col-lg-offset-2" style=" margin-top: 3vh; padding:15px;">
  <div class="portlet light">
    <div class="portlet-title">
        <div class="caption font-red-sunglo">
          <span class="caption-subject bold uppercase" style="font-size:24px">Create Push Notification</span><br />
        </div>
        <div class="actions">
          <%= link_to :back, :class => "btn btn-circle btn-icon-only red" do %>
            <i class="icon-trash"></i>
          <% end %>
          <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
        </div>
    </div>
    <div class="portlet-body form">
      <%= form_for(@push_notification) do |f| %>
        <% if @push_notification.errors.any? %>
          <div style="visibility: hidden; height:0;">
            <%= flash[:notice] = @push_notification.errors.full_messages %>
          </div>
        <% end %>
        <div class="form-group form-md-line-input form-md-floating-label">
            <!-- <textarea class="form-control" rows="3" maxlength="256"></textarea> -->
             <%= f.text_area :message, class: "form-control", rows: 3, maxlength: 256 %>
            <label for="form_control_1">Message Text</label>
            <span class="help-block" >Push Notification has a max of 256 characters...</span>
        </div>

        <h3 style="font-size: 16px; color: #999; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;font-weight: 800; letter-spacing: .2px;">Dealership Members</h3>

        <table class="table table-striped table-bordered table-hover table-checkable order-column" id="users_notifications_checkbox_table">
            <thead>
                <tr>
                    <th>
                        <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                            <input type="checkbox" class="group-checkable" data-set="#users_notifications_checkbox_table .checkboxes" />
                            <span></span>
                        </label>
                    </th>
                    <th> Name </th>
                    <th> Email </th>
                    <th> Joined </th>
                </tr>
            </thead>
            <tbody>
              <% User.where.not('device_token' => nil).each do |user| %>
                <tr class="odd gradeX">
                  <td>
                      <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                        <%= check_box_tag 'tokens[]', user.id, false, :class => 'checkboxes' %>
                          <span></span>
                      </label>
                  </td>
                  <td><%= user.name %></td>
                  <td><%= user.email %></td>
                  <td style="text-align:center; "><%= user.created_at.strftime("%m/%d/%Y") %></td>
                </tr>
              <% end %>
            </tbody>
        </table>
        <div class="row" style="text-align:center">
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.submit "Send", :type => "submit", :class=>"btn btn-primary", :style=>"border-radius: 5px !important; margin-top:10px; background: #FF5252; font-family: 'Muli', 'Helvetica', 'Arial', 'sans-serif'; text-shadow:none; font-variant:none; width: 92%; margin-top:30px" %>
        </div>
        <% end %>
      </div>
    </div>                    <!-- END EXAMPLE TABLE PORTLET-->
  </div>